### PR TITLE
Add Benchmarks

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/sroar/1)

### CODE REVIEW

**Review by manishrjain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/sroar/1)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @manishrjain)

___
*[bitmap.go, line 76 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQHjxk24eXiRfUtSgm:-MZQHjxk24eXiRfUtSgn:b-otj4q8) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L76)):*
> ```Go
> 	// Always generate a container for key = 0x00. Otherwise, node gets confused about whether a
> 	// zero key is a new key or not.
> 	offset := ra.newContainer(maxSizeOfContainer)
> ```

Why use maxSize?
___
*[bitmap.go, line 78 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQHl_AAisii0iLZGzq:-MZQHl_AAisii0iLZGzr:b237c0m) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L78)):*
> ```Go
> 	offset := ra.newContainer(maxSizeOfContainer)
> 	ra.keys.setAt(indexStart+1, offset) // First two are for num keys. index=2 -> 0 key. index=3 -> offset.
> 	ra.keys.setNumKeys(indexNumKeys)
> ```

Why is setNumKeys being set to an index const? index consts are for offsets, not values.
___
*[bitmap.go, line 118 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQI0AW40aDRTZDCSQ3:-MZQI0AW40aDRTZDCSQ4:b-kga8zq) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L118)):*
> ```Go
> 
> func (ra *Bitmap) fastExpand(bySize uint16) {
> 	if len(ra.data) > int(ra.keys[indexOffset])+int(bySize) {
> ```

I don't quite understand this. Doesn't ra.data always reflect the latest length? When do we shrink it?

Also, what is indexOffset? Are we tracking the length of ra.data in this? Why?

**Comment by ahsanbarkati** [comment]
___
*[bitmap.go, line 78 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQHl_AAisii0iLZGzq:-MZRTCQT3JSal8NWvly9:b9rex6q) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L78)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why is setNumKeys being set to an index const? index consts are for offsets, not values.
</blockquote></details>

That's correct. It was just by mistake that I put indexNumKeys instead of 1.

**Comment by ahsanbarkati** [comment]
___
*[bitmap.go, line 76 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQHjxk24eXiRfUtSgm:-MZRTWTe9LTDUvpgxQXO:b-2i6phf) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L76)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why use maxSize?
</blockquote></details>

Changed it to min.

**Comment by ahsanbarkati** [comment]
___
*[bitmap.go, line 118 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQI0AW40aDRTZDCSQ3:-MZRT_CX7eFDecQvLkCE:b-usv6n) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L118)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I don't quite understand this. Doesn't ra.data always reflect the latest length? When do we shrink it?

Also, what is indexOffset? Are we tracking the length of ra.data in this? Why?
</blockquote></details>

I have been experimenting this, I made ra.data to contain some extra space, So that we don't expand always. `IndexOffset` is the offset until which we have used ra.data

**Review by manishrjain — COMMENTED** [review]
:lgtm: Clean this up a bit and get this merged.

> Reviewed 6 of 9 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/sroar/1#-:-M_MDFbm7FpUSWbQWOcB:b-boi02a)* status: all files reviewed, 2 unresolved discussions (waiting on @ahsanbarkati)

___
*[benchmark_test.go, line 37 at r3](https://reviewable.io/reviews/dgraph-io/sroar/1#-M_MBT38At8omxq1vX7t:-M_MBT38At8omxq1vX7u:b-meg0r) ([raw file](https://github.com/dgraph-io/sroar/blob/0a800096e2eee295549cd5d4bc29a131d2ac6096/benchmark_test.go#L37)):*
> ```Go
> 		var i uint64
> 		for i = 0; i <= max-incr; i += incr {
> 			rb.Add(i)
> ```

Keep this to Set.
___
*[bitmap.go, line 118 at r1](https://reviewable.io/reviews/dgraph-io/sroar/1#-MZQI0AW40aDRTZDCSQ3:-M_MCmrC5SYO50OFiPPM:b-zaaus8) ([raw file](https://github.com/dgraph-io/sroar/blob/8a7029e6bbdfa3a28b2f2b685e3272e3e1bb06d3/bitmap.go#L118)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

I have been experimenting this, I made ra.data to contain some extra space, So that we don't expand always. `IndexOffset` is the offset until which we have used ra.data
</blockquote></details>

For now, avoid the complexity.

**Pull request merged**
